# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(599, 549)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/g960.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.nooc = QtWidgets.QSpinBox(Dialog)
        self.nooc.setGeometry(QtCore.QRect(287, 70, 291, 31))
        self.nooc.setMinimum(1)
        self.nooc.setMaximum(999999999)
        self.nooc.setObjectName("nooc")
        self.bondui = QtWidgets.QSlider(Dialog)
        self.bondui.setGeometry(QtCore.QRect(376, 107, 201, 31))
        self.bondui.setToolTipDuration(2)
        self.bondui.setMinimum(1)
        self.bondui.setMaximum(3)
        self.bondui.setPageStep(1)
        self.bondui.setOrientation(QtCore.Qt.Horizontal)
        self.bondui.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.bondui.setTickInterval(1)
        self.bondui.setObjectName("bondui")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(456, 520, 91, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/logo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 520, 31, 23))
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 520, 181, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.placer = QtWidgets.QSlider(Dialog)
        self.placer.setEnabled(False)
        self.placer.setGeometry(QtCore.QRect(20, 170, 491, 31))
        self.placer.setToolTipDuration(2)
        self.placer.setMinimum(2)
        self.placer.setMaximum(3)
        self.placer.setPageStep(1)
        self.placer.setOrientation(QtCore.Qt.Horizontal)
        self.placer.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.placer.setTickInterval(1)
        self.placer.setObjectName("placer")
        self.placertxt = QtWidgets.QTextEdit(Dialog)
        self.placertxt.setEnabled(False)
        self.placertxt.setGeometry(QtCore.QRect(520, 170, 61, 31))
        self.placertxt.setObjectName("placertxt")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 0, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 40, 371, 16))
        font = QtGui.QFont()
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("letter-spacing:normal;\n"
"")
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 60, 571, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 140, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 61, 51))
        self.label_6.setText("")
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setPixmap(QtGui.QPixmap(":/res/logo.svg"))
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.abt = QtWidgets.QPushButton(Dialog)
        self.abt.setGeometry(QtCore.QRect(14, 520, 31, 23))
        self.abt.setToolTipDuration(2)
        self.abt.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/res/ss-branding.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.abt.setIcon(icon3)
        self.abt.setObjectName("abt")
        self.output = QtWidgets.QLabel(Dialog)
        self.output.setGeometry(QtCore.QRect(20, 280, 561, 211))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.output.setFont(font)
        self.output.setStyleSheet("color: rgb(248, 248, 248);\n"
"background-color: rgb(63, 63, 63);")
        self.output.setAlignment(QtCore.Qt.AlignCenter)
        self.output.setWordWrap(True)
        self.output.setObjectName("output")
        self.bondtxt = QtWidgets.QLabel(Dialog)
        self.bondtxt.setGeometry(QtCore.QRect(290, 110, 71, 21))
        self.bondtxt.setAutoFillBackground(False)
        self.bondtxt.setStyleSheet("border-color: rgb(117, 117, 117);\n"
"gridline-color: rgb(117, 117, 117);\n"
"background-color: rgb(212, 212, 212);")
        self.bondtxt.setTextFormat(QtCore.Qt.AutoText)
        self.bondtxt.setAlignment(QtCore.Qt.AlignCenter)
        self.bondtxt.setObjectName("bondtxt")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(20, 200, 361, 20))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setEnabled(True)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 220, 361, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QtCore.QRect(520, 240, 61, 31))
        self.pushButton_4.setToolTipDuration(1)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.output_lo2 = QtWidgets.QLabel(Dialog)
        self.output_lo2.setGeometry(QtCore.QRect(16, 405, 561, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.output_lo2.setFont(font)
        self.output_lo2.setStyleSheet("color: rgb(248, 248, 248);\n"
"background-color: rgb(63, 63, 63,0);")
        self.output_lo2.setText("")
        self.output_lo2.setAlignment(QtCore.Qt.AlignCenter)
        self.output_lo2.setWordWrap(True)
        self.output_lo2.setObjectName("output_lo2")
        self.output_hi2 = QtWidgets.QLabel(Dialog)
        self.output_hi2.setGeometry(QtCore.QRect(17, 335, 561, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.output_hi2.setFont(font)
        self.output_hi2.setStyleSheet("color: rgb(248, 248, 248);\n"
"background-color: rgb(63, 63, 63,0);")
        self.output_hi2.setText("")
        self.output_hi2.setAlignment(QtCore.Qt.AlignCenter)
        self.output_hi2.setWordWrap(True)
        self.output_hi2.setObjectName("output_hi2")
        self.output_hi1 = QtWidgets.QLabel(Dialog)
        self.output_hi1.setGeometry(QtCore.QRect(20, 350, 561, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.output_hi1.setFont(font)
        self.output_hi1.setToolTipDuration(2)
        self.output_hi1.setStyleSheet("color: rgb(248, 248, 248);\n"
"background-color: rgb(63, 63, 63, 0);")
        self.output_hi1.setText("")
        self.output_hi1.setAlignment(QtCore.Qt.AlignCenter)
        self.output_hi1.setWordWrap(True)
        self.output_hi1.setObjectName("output_hi1")
        self.output_lo1 = QtWidgets.QLabel(Dialog)
        self.output_lo1.setGeometry(QtCore.QRect(20, 390, 561, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.output_lo1.setFont(font)
        self.output_lo1.setStyleSheet("color: rgb(248, 248, 248);\n"
"background-color: rgb(63, 63, 63, 0);")
        self.output_lo1.setText("")
        self.output_lo1.setAlignment(QtCore.Qt.AlignCenter)
        self.output_lo1.setWordWrap(True)
        self.output_lo1.setObjectName("output_lo1")
        self.abt_2 = QtWidgets.QPushButton(Dialog)
        self.abt_2.setGeometry(QtCore.QRect(50, 520, 91, 23))
        self.abt_2.setToolTipDuration(2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/res/github.logo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.abt_2.setIcon(icon4)
        self.abt_2.setObjectName("abt_2")
        self.textEdit = QtWidgets.QLineEdit(Dialog)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(20, 240, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"gridline-color: rgb(255, 255, 255);")
        self.textEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.textEdit.setClearButtonEnabled(True)
        self.textEdit.setObjectName("textEdit")
        self.output_hi3 = QtWidgets.QLabel(Dialog)
        self.output_hi3.setGeometry(QtCore.QRect(20, 320, 561, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.output_hi3.setFont(font)
        self.output_hi3.setStyleSheet("color: rgb(248, 248, 248);\n"
"background-color: rgb(63, 63, 63,0);")
        self.output_hi3.setText("")
        self.output_hi3.setAlignment(QtCore.Qt.AlignCenter)
        self.output_hi3.setWordWrap(True)
        self.output_hi3.setObjectName("output_hi3")
        self.output_lo3 = QtWidgets.QLabel(Dialog)
        self.output_lo3.setGeometry(QtCore.QRect(20, 420, 561, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.output_lo3.setFont(font)
        self.output_lo3.setStyleSheet("color: rgb(248, 248, 248);\n"
"background-color: rgb(63, 63, 63,0);")
        self.output_lo3.setText("")
        self.output_lo3.setAlignment(QtCore.Qt.AlignCenter)
        self.output_lo3.setWordWrap(True)
        self.output_lo3.setObjectName("output_lo3")
        self.output_lo2_2 = QtWidgets.QLabel(Dialog)
        self.output_lo2_2.setGeometry(QtCore.QRect(20, 403, 561, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.output_lo2_2.setFont(font)
        self.output_lo2_2.setStyleSheet("color: rgb(248, 248, 248);\n"
"background-color: rgb(63, 63, 63,0);")
        self.output_lo2_2.setText("")
        self.output_lo2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.output_lo2_2.setWordWrap(True)
        self.output_lo2_2.setObjectName("output_lo2_2")
        self.output_hi2_2 = QtWidgets.QLabel(Dialog)
        self.output_hi2_2.setGeometry(QtCore.QRect(20, 337, 561, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.output_hi2_2.setFont(font)
        self.output_hi2_2.setStyleSheet("color: rgb(248, 248, 248);\n"
"background-color: rgb(63, 63, 63,0);")
        self.output_hi2_2.setText("")
        self.output_hi2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.output_hi2_2.setWordWrap(True)
        self.output_hi2_2.setObjectName("output_hi2_2")
        self.output_lo1_2 = QtWidgets.QLabel(Dialog)
        self.output_lo1_2.setGeometry(QtCore.QRect(20, 390, 561, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.output_lo1_2.setFont(font)
        self.output_lo1_2.setStyleSheet("color: rgb(248, 248, 248);\n"
"background-color: rgb(63, 63, 63, 0);")
        self.output_lo1_2.setText("")
        self.output_lo1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.output_lo1_2.setWordWrap(True)
        self.output_lo1_2.setObjectName("output_lo1_2")
        self.output_hi1_2 = QtWidgets.QLabel(Dialog)
        self.output_hi1_2.setGeometry(QtCore.QRect(20, 350, 561, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.output_hi1_2.setFont(font)
        self.output_hi1_2.setToolTipDuration(2)
        self.output_hi1_2.setStyleSheet("color: rgb(248, 248, 248);\n"
"background-color: rgb(63, 63, 63, 0);")
        self.output_hi1_2.setText("")
        self.output_hi1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.output_hi1_2.setWordWrap(True)
        self.output_hi1_2.setObjectName("output_hi1_2")
        self.msgOut = QtWidgets.QLabel(Dialog)
        self.msgOut.setGeometry(QtCore.QRect(20, 490, 561, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.msgOut.setFont(font)
        self.msgOut.setStyleSheet("color: rgb(248, 248, 248);\n"
"background-color: rgb(100, 100, 100);")
        self.msgOut.setText("")
        self.msgOut.setAlignment(QtCore.Qt.AlignCenter)
        self.msgOut.setWordWrap(True)
        self.msgOut.setObjectName("msgOut")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "carbonic"))
        self.bondui.setToolTip(_translate("Dialog", "Drag the slider to choose between alkane, alkene and alkyne"))
        self.pushButton.setText(_translate("Dialog", "COMPUTE"))
        self.pushButton_3.setToolTip(_translate("Dialog", "Place the Bond in Alkene and Alkyne type and then update the equation in the output box"))
        self.pushButton_3.setText(_translate("Dialog", "PLACE BOND && UPDATE EQN"))
        self.placer.setToolTip(_translate("Dialog", "Drag the slider to chose the position of the double / triple bond."))
        self.label.setText(_translate("Dialog", "carbonic™"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p>by srevinsaju on <a href=\" https://github.com/srevinsaju/carbonic\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/srevinsaju/carbonic</span></a></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "Bond : Alkane/Alkene/Alkyne"))
        self.label_3.setText(_translate("Dialog", "Number of Carbon atoms"))
        self.label_5.setText(_translate("Dialog", "Position of Alkene / Alkane bond (can be added on consecutively)"))
        self.abt.setToolTip(_translate("Dialog", "Created by Srevin Saju (@srevinsaju). Licensed under Affereo GPL v3.0 License. Read README.md for more information"))
        self.output.setText(_translate("Dialog", "-- OUTPUT --"))
        self.bondtxt.setText(_translate("Dialog", "ALKANE"))
        self.radioButton.setText(_translate("Dialog", "Enter above details"))
        self.radioButton_2.setText(_translate("Dialog", "Enter the IUPAC name (experimental, only Alkane upto 100)"))
        self.pushButton_4.setToolTip(_translate("Dialog", "Press GO to compute from IUPAC name"))
        self.pushButton_4.setText(_translate("Dialog", "GO"))
        self.output_hi1.setToolTip(_translate("Dialog", "Output box"))
        self.abt_2.setToolTip(_translate("Dialog", "View the Readme.md on Github, the leader in opensource software for free"))
        self.abt_2.setText(_translate("Dialog", "Learn more"))
        self.textEdit.setPlaceholderText(_translate("Dialog", "eg: [2-methyl,3-ethyl]4-dodecene"))
        self.output_hi1_2.setToolTip(_translate("Dialog", "Output box"))


import res_rc
